apiVersion: web.example.com/v1
kind: WebSite
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: website-sample
spec:
  # TODO(user): Add fields here
